# version: 0.2

# env:
#   variables:
#     IMAGE_REPO: "ghcr.io/yuuking0304/ectr_dev_i231_sample"
#   parameter-store:
#     PAT: "PAT"

# phases:
#   pre_build:
#     commands:
#       - echo Logging in to GitHub Container Registry...
#       - docker login ghcr.io -u yuuking0304 -p ${PAT}

#       - REPOSITORY_URI=$IMAGE_REPO
#       - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
#       - IMAGE_TAG=${COMMIT_HASH:=latest}
#   build:
#     commands:
#       - echo Build started on `date`
#       - echo Building the Docker image...
#       - docker build -t $REPOSITORY_URI:latest .
#       - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
#   post_build:
#     commands:
#       - echo Build completed on `date`
#       - echo Pushing the Docker images...
#       - docker push $REPOSITORY_URI:latest
#       - docker push $REPOSITORY_URI:$IMAGE_TAG
